name: 生成 UnityAds Dylib

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: 📥 取得程式碼
        uses: actions/checkout@v4

      - name: 🛠️ 安裝編譯工具與 ldid (修正簽名報錯)
        run: |
          # 1. 安裝蓋章工具 ldid
          brew install ldid
          
          # 2. 光速安裝 Theos
          git clone --recursive --depth 1 https://github.com/theos/theos.git ~/theos
          rm -rf ~/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks
          
          # 3. 註冊環境變數
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: 🚀 開始編譯 (Make)
        run: |
          # 自動生成 Swift 鑰匙
          touch Dummy.swift
          
          make clean
          make
        env:
          THEOS: ~/theos

      - name: 📦 打包並交出 Dylib 檔案
        uses: actions/upload-artifact@v4
        with:
          name: UnityAds_Compiled_Dylib
          # 修正路徑，直接去抓生成的 dylib
          path: .theos/obj/debug/*.dylib
